body:
  - type: input
    attributes:
      name: account
      label: WiFi account
      defaultValue: B21090519
  - type: passwordBox
    attributes:
      name: password
      label: Password input
      defaultValue: '123456'